// Mock categories data
export const mockCategories = [
  { id: 1, name: "Hair" },
  { id: 2, name: "Nails" },
  { id: 3, name: "Makeup" },
  { id: 4, name: "Barbing Saloon" },
];

// Mock vendors data
export const mockVendors = [
  // --- Hair ---
  {
    id: 1,
    name: "Alison Leema",
    categoryId: 1,
    type: "In-shop",
    rating: 4.0,
    distance: 2.5,
    image: require("../../assets/img/blackman.jpg"),
  },
  {
    id: 2,
    name: "Temilolu",
    categoryId: 1,
    type: "Home Service",
    rating: 4.0,
    distance: 2.8,
    image: require("../../assets/img/priti.svg"),
  },
  {
    id: 3,
    name: "Chuka Obi",
    categoryId: 1,
    type: "In-shop",
    rating: 4.0,
    distance: 1.2,
    image: require("../../assets/img/alex.svg"),
  },
  {
    id: 4,
    name: "Ngozi Okafor",
    categoryId: 1,
    type: "Home Service",
    rating: 4.0,
    distance: 2.9,
    image: require("../../assets/img/ayo.svg"),
  },
  {
    id: 5,
    name: "Hair by Ire",
    categoryId: 1,
    type: "In-shop",
    rating: 4.0,
    distance: 2.7,
    image: require("../../assets/img/facials.png"),
  },
  {
    id: 6,
    name: "Beauty by Sade",
    categoryId: 1,
    type: "Home Service",
    rating: 4.0,
    distance: 2.1,
    image: require("../../assets/img/nailtech.jpg"),
  },
  {
    id: 7,
    name: "Glow Up Studio",
    categoryId: 1,
    type: "In-shop",
    rating: 4.0,
    distance: 2.3,
    image: require("../../assets/img/ped.jpg"),
  },
  {
    id: 8,
    name: "Hair by Ire",
    categoryId: 1,
    type: "Home Service",
    rating: 4.0,
    distance: 5.2,
    image: require("../../assets/img/product1.jpg"),
  },
  {
    id: 9,
    name: "Hair by Ire",
    categoryId: 1,
    type: "In-shop",
    rating: 4.0,
    distance: 4.8,
    image: require("../../assets/img/product2.jpg"),
  },
  {
    id: 10,
    name: "Hair by Ire",
    categoryId: 1,
    type: "Home Service",
    rating: 4.0,
    distance: 6.1,
    image: require("../../assets/img/product3.jpg"),
  },
  // --- Nails ---
  {
    id: 11,
    name: "Nail Queen",
    categoryId: 2,
    type: "In-shop",
    rating: 4.5,
    distance: 1.5,
    image: require("../../assets/img/nailtech.jpg"),
  },
  {
    id: 12,
    name: "Nails by Ada",
    categoryId: 2,
    type: "Home Service",
    rating: 4.2,
    distance: 2.2,
    image: require("../../assets/img/product4.jpg"),
  },
  {
    id: 13,
    name: "Pretty Nails",
    categoryId: 2,
    type: "In-shop",
    rating: 4.7,
    distance: 2.8,
    image: require("../../assets/img/product5.jpg"),
  },
  {
    id: 14,
    name: "Nail Artistry",
    categoryId: 2,
    type: "Home Service",
    rating: 4.3,
    distance: 2.9,
    image: require("../../assets/img/product6.jpg"),
  },
  {
    id: 15,
    name: "Nail Studio",
    categoryId: 2,
    type: "In-shop",
    rating: 4.0,
    distance: 2.6,
    image: require("../../assets/img/nailtech.jpg"),
  },
  {
    id: 16,
    name: "Nail Spa",
    categoryId: 2,
    type: "Home Service",
    rating: 4.1,
    distance: 2.7,
    image: require("../../assets/img/product1.jpg"),
  },
  {
    id: 17,
    name: "Nail Pro",
    categoryId: 2,
    type: "In-shop",
    rating: 4.4,
    distance: 2.3,
    image: require("../../assets/img/product2.jpg"),
  },
  {
    id: 18,
    name: "Nail by Ire",
    categoryId: 2,
    type: "Home Service",
    rating: 4.0,
    distance: 4.2,
    image: require("../../assets/img/product3.jpg"),
  },
  {
    id: 19,
    name: "Nail by Sade",
    categoryId: 2,
    type: "In-shop",
    rating: 4.0,
    distance: 5.1,
    image: require("../../assets/img/product4.jpg"),
  },
  {
    id: 20,
    name: "Nail by Glow",
    categoryId: 2,
    type: "Home Service",
    rating: 4.0,
    distance: 6.3,
    image: require("../../assets/img/product5.jpg"),
  },
  // --- Makeup ---
  {
    id: 21,
    name: "Makeup by Tola",
    categoryId: 3,
    type: "In-shop",
    rating: 4.6,
    distance: 2.1,
    image: require("../../assets/img/makeuppromo.png"),
  },
  {
    id: 22,
    name: "Glam by Sade",
    categoryId: 3,
    type: "Home Service",
    rating: 4.5,
    distance: 2.7,
    image: require("../../assets/img/product6.jpg"),
  },
  {
    id: 23,
    name: "Beauty Glam",
    categoryId: 3,
    type: "In-shop",
    rating: 4.8,
    distance: 2.9,
    image: require("../../assets/img/product1.jpg"),
  },
  {
    id: 24,
    name: "Makeup Studio",
    categoryId: 3,
    type: "Home Service",
    rating: 4.2,
    distance: 2.5,
    image: require("../../assets/img/product2.jpg"),
  },
  {
    id: 25,
    name: "Glamour Pro",
    categoryId: 3,
    type: "In-shop",
    rating: 4.0,
    distance: 2.8,
    image: require("../../assets/img/product3.jpg"),
  },
  {
    id: 26,
    name: "Makeup Pro",
    categoryId: 3,
    type: "Home Service",
    rating: 4.1,
    distance: 2.3,
    image: require("../../assets/img/product4.jpg"),
  },
  {
    id: 27,
    name: "Glam Up",
    categoryId: 3,
    type: "In-shop",
    rating: 4.3,
    distance: 2.6,
    image: require("../../assets/img/product5.jpg"),
  },
  {
    id: 28,
    name: "Makeup by Glow",
    categoryId: 3,
    type: "Home Service",
    rating: 4.0,
    distance: 4.2,
    image: require("../../assets/img/product6.jpg"),
  },
  {
    id: 29,
    name: "Makeup by Ire",
    categoryId: 3,
    type: "In-shop",
    rating: 4.0,
    distance: 5.1,
    image: require("../../assets/img/product1.jpg"),
  },
  {
    id: 30,
    name: "Makeup by Sade",
    categoryId: 3,
    type: "Home Service",
    rating: 4.0,
    distance: 6.3,
    image: require("../../assets/img/product2.jpg"),
  },
  // --- Barbing Saloon ---
  {
    id: 31,
    name: "Sharp Cuts",
    categoryId: 4,
    type: "In-shop",
    rating: 4.7,
    distance: 2.2,
    image: require("../../assets/img/blackman.jpg"),
  },
  {
    id: 32,
    name: "Barber King",
    categoryId: 4,
    type: "Home Service",
    rating: 4.5,
    distance: 2.8,
    image: require("../../assets/img/priti.svg"),
  },
  {
    id: 33,
    name: "Fresh Fades",
    categoryId: 4,
    type: "In-shop",
    rating: 4.6,
    distance: 2.9,
    image: require("../../assets/img/alex.svg"),
  },
  {
    id: 34,
    name: "Barber Pro",
    categoryId: 4,
    type: "Home Service",
    rating: 4.2,
    distance: 2.5,
    image: require("../../assets/img/ayo.svg"),
  },
  {
    id: 35,
    name: "Barber Studio",
    categoryId: 4,
    type: "In-shop",
    rating: 4.0,
    distance: 2.7,
    image: require("../../assets/img/facials.png"),
  },
  {
    id: 36,
    name: "Barber Spa",
    categoryId: 4,
    type: "Home Service",
    rating: 4.1,
    distance: 2.3,
    image: require("../../assets/img/nailtech.jpg"),
  },
  {
    id: 37,
    name: "Barber Glow",
    categoryId: 4,
    type: "In-shop",
    rating: 4.3,
    distance: 2.6,
    image: require("../../assets/img/ped.jpg"),
  },
  {
    id: 38,
    name: "Barber by Ire",
    categoryId: 4,
    type: "Home Service",
    rating: 4.0,
    distance: 4.2,
    image: require("../../assets/img/product1.jpg"),
  },
  {
    id: 39,
    name: "Barber by Sade",
    categoryId: 4,
    type: "In-shop",
    rating: 4.0,
    distance: 5.1,
    image: require("../../assets/img/product2.jpg"),
  },
  {
    id: 40,
    name: "Barber by Glow",
    categoryId: 4,
    type: "Home Service",
    rating: 4.0,
    distance: 6.3,
    image: require("../../assets/img/product3.jpg"),
  },
];
